package com.huihuan.eme.domain.db;
// Generated 2016-2-21 10:11:30 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AqiInfo generated by hbm2java
 */
@Entity
@Table(name="aqi_info"
    ,catalog="eme"
)
public class AqiInfo  implements java.io.Serializable {


     private Long id;
     private Float ilow;
     private Float ihigh;
     private String lvl;
     private String description;
     private String colorDescription;
     private String color;
     private String healthDescription;
     private String advice;
     private Set<IaqiInfo> iaqiInfos = new HashSet<IaqiInfo>(0);

    public AqiInfo() {
    }

    public AqiInfo(Float ilow, Float ihigh, String lvl, String description, String colorDescription, String color, String healthDescription, String advice, Set<IaqiInfo> iaqiInfos) {
       this.ilow = ilow;
       this.ihigh = ihigh;
       this.lvl = lvl;
       this.description = description;
       this.colorDescription = colorDescription;
       this.color = color;
       this.healthDescription = healthDescription;
       this.advice = advice;
       this.iaqiInfos = iaqiInfos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="ilow", precision=12, scale=0)
    public Float getIlow() {
        return this.ilow;
    }
    
    public void setIlow(Float ilow) {
        this.ilow = ilow;
    }
    
    @Column(name="ihigh", precision=12, scale=0)
    public Float getIhigh() {
        return this.ihigh;
    }
    
    public void setIhigh(Float ihigh) {
        this.ihigh = ihigh;
    }
    
    @Column(name="lvl", length=20)
    public String getLvl() {
        return this.lvl;
    }
    
    public void setLvl(String lvl) {
        this.lvl = lvl;
    }
    
    @Column(name="description", length=20)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="color_description", length=20)
    public String getColorDescription() {
        return this.colorDescription;
    }
    
    public void setColorDescription(String colorDescription) {
        this.colorDescription = colorDescription;
    }
    
    @Column(name="color", length=20)
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    
    @Column(name="health_description", length=64)
    public String getHealthDescription() {
        return this.healthDescription;
    }
    
    public void setHealthDescription(String healthDescription) {
        this.healthDescription = healthDescription;
    }
    
    @Column(name="advice", length=64)
    public String getAdvice() {
        return this.advice;
    }
    
    public void setAdvice(String advice) {
        this.advice = advice;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="aqiInfo")
    public Set<IaqiInfo> getIaqiInfos() {
        return this.iaqiInfos;
    }
    
    public void setIaqiInfos(Set<IaqiInfo> iaqiInfos) {
        this.iaqiInfos = iaqiInfos;
    }




}


