package com.huihuan.eme.domain.db;
// Generated 2016-3-3 16:33:56 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DetectFactor generated by hbm2java
 */
@Entity
@Table(name="detect_factor"
    ,catalog="eme"
)
public class DetectFactor  implements java.io.Serializable {


     private Long id;
     private DetectCategory detectCategory;
     private DetectContentDic detectContentDic;
     private String factorName;
     private float nadir;
     private Float utopia;
     private Float reservation;
     private Float aspiration;
     private String unit;
     private Long frequency;
     private Set<DetectHistory> detectHistories = new HashSet<DetectHistory>(0);
     private Set<IaqiInfo> iaqiInfos = new HashSet<IaqiInfo>(0);
     private Set<DetectAir> detectAirs = new HashSet<DetectAir>(0);
     private Set<Detect> detects = new HashSet<Detect>(0);

    public DetectFactor() {
    }

	
    public DetectFactor(float nadir) {
        this.nadir = nadir;
    }
    public DetectFactor(DetectCategory detectCategory, DetectContentDic detectContentDic, String factorName, float nadir, Float utopia, Float reservation, Float aspiration, String unit, Long frequency, Set<DetectHistory> detectHistories, Set<IaqiInfo> iaqiInfos, Set<DetectAir> detectAirs, Set<Detect> detects) {
       this.detectCategory = detectCategory;
       this.detectContentDic = detectContentDic;
       this.factorName = factorName;
       this.nadir = nadir;
       this.utopia = utopia;
       this.reservation = reservation;
       this.aspiration = aspiration;
       this.unit = unit;
       this.frequency = frequency;
       this.detectHistories = detectHistories;
       this.iaqiInfos = iaqiInfos;
       this.detectAirs = detectAirs;
       this.detects = detects;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_detect_category")
    public DetectCategory getDetectCategory() {
        return this.detectCategory;
    }
    
    public void setDetectCategory(DetectCategory detectCategory) {
        this.detectCategory = detectCategory;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_detect_content")
    public DetectContentDic getDetectContentDic() {
        return this.detectContentDic;
    }
    
    public void setDetectContentDic(DetectContentDic detectContentDic) {
        this.detectContentDic = detectContentDic;
    }
    
    @Column(name="factor_name", length=64)
    public String getFactorName() {
        return this.factorName;
    }
    
    public void setFactorName(String factorName) {
        this.factorName = factorName;
    }
    
    @Column(name="nadir", nullable=false, precision=12, scale=0)
    public float getNadir() {
        return this.nadir;
    }
    
    public void setNadir(float nadir) {
        this.nadir = nadir;
    }
    
    @Column(name="utopia", precision=12, scale=0)
    public Float getUtopia() {
        return this.utopia;
    }
    
    public void setUtopia(Float utopia) {
        this.utopia = utopia;
    }
    
    @Column(name="reservation", precision=12, scale=0)
    public Float getReservation() {
        return this.reservation;
    }
    
    public void setReservation(Float reservation) {
        this.reservation = reservation;
    }
    
    @Column(name="aspiration", precision=12, scale=0)
    public Float getAspiration() {
        return this.aspiration;
    }
    
    public void setAspiration(Float aspiration) {
        this.aspiration = aspiration;
    }
    
    @Column(name="unit", length=20)
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }
    
    @Column(name="frequency")
    public Long getFrequency() {
        return this.frequency;
    }
    
    public void setFrequency(Long frequency) {
        this.frequency = frequency;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="detectFactor")
    public Set<DetectHistory> getDetectHistories() {
        return this.detectHistories;
    }
    
    public void setDetectHistories(Set<DetectHistory> detectHistories) {
        this.detectHistories = detectHistories;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="detectFactor")
    public Set<IaqiInfo> getIaqiInfos() {
        return this.iaqiInfos;
    }
    
    public void setIaqiInfos(Set<IaqiInfo> iaqiInfos) {
        this.iaqiInfos = iaqiInfos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="detectFactor")
    public Set<DetectAir> getDetectAirs() {
        return this.detectAirs;
    }
    
    public void setDetectAirs(Set<DetectAir> detectAirs) {
        this.detectAirs = detectAirs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="detectFactor")
    public Set<Detect> getDetects() {
        return this.detects;
    }
    
    public void setDetects(Set<Detect> detects) {
        this.detects = detects;
    }




}


