package com.huihuan.eme.domain.db;
// Generated 2016-3-15 21:08:08 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DetectContentDic generated by hbm2java
 */
@Entity
@Table(name="detect_content_dic"
    ,catalog="eme"
)
public class DetectContentDic  implements java.io.Serializable {


     private Long id;
     private String detectContent;
     private Set<DetectAirReport> detectAirReports = new HashSet<DetectAirReport>(0);
     private Set<DetectFactor> detectFactors = new HashSet<DetectFactor>(0);
     private Set<DetectStationContent> detectStationContents = new HashSet<DetectStationContent>(0);

    public DetectContentDic() {
    }

    public DetectContentDic(String detectContent, Set<DetectAirReport> detectAirReports, Set<DetectFactor> detectFactors, Set<DetectStationContent> detectStationContents) {
       this.detectContent = detectContent;
       this.detectAirReports = detectAirReports;
       this.detectFactors = detectFactors;
       this.detectStationContents = detectStationContents;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="detect_content", length=64)
    public String getDetectContent() {
        return this.detectContent;
    }
    
    public void setDetectContent(String detectContent) {
        this.detectContent = detectContent;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="detectContentDic")
    public Set<DetectAirReport> getDetectAirReports() {
        return this.detectAirReports;
    }
    
    public void setDetectAirReports(Set<DetectAirReport> detectAirReports) {
        this.detectAirReports = detectAirReports;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="detectContentDic")
    public Set<DetectFactor> getDetectFactors() {
        return this.detectFactors;
    }
    
    public void setDetectFactors(Set<DetectFactor> detectFactors) {
        this.detectFactors = detectFactors;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="detectContentDic")
    public Set<DetectStationContent> getDetectStationContents() {
        return this.detectStationContents;
    }
    
    public void setDetectStationContents(Set<DetectStationContent> detectStationContents) {
        this.detectStationContents = detectStationContents;
    }




}


