package com.huihuan.eme.domain.db;
// Generated 2016-3-3 16:33:56 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DetectAirReport generated by hbm2java
 */
@Entity
@Table(name="detect_air_report"
    ,catalog="eme"
)
public class DetectAirReport  implements java.io.Serializable {


     private Long id;
     private DetectStation detectStation;
     private DetectContentDic detectContentDic;
     private AqiInfo aqiInfo;
     private Date reportTime;
     private Boolean isDaily;
     private Float aqi;
     private Float so2Aqi;
     private Float o3Aqi;
     private Float no2Aqi;
     private Float pm10Aqi;
     private Float pm25Aqi;
     private Float coAqi;

    public DetectAirReport() {
    }

    public DetectAirReport(DetectStation detectStation, DetectContentDic detectContentDic, AqiInfo aqiInfo, Date reportTime, Boolean isDaily, Float aqi, Float so2Aqi, Float o3Aqi, Float no2Aqi, Float pm10Aqi, Float pm25Aqi, Float coAqi) {
       this.detectStation = detectStation;
       this.detectContentDic = detectContentDic;
       this.aqiInfo = aqiInfo;
       this.reportTime = reportTime;
       this.isDaily = isDaily;
       this.aqi = aqi;
       this.so2Aqi = so2Aqi;
       this.o3Aqi = o3Aqi;
       this.no2Aqi = no2Aqi;
       this.pm10Aqi = pm10Aqi;
       this.pm25Aqi = pm25Aqi;
       this.coAqi = coAqi;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_detect_station")
    public DetectStation getDetectStation() {
        return this.detectStation;
    }
    
    public void setDetectStation(DetectStation detectStation) {
        this.detectStation = detectStation;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_detect_content")
    public DetectContentDic getDetectContentDic() {
        return this.detectContentDic;
    }
    
    public void setDetectContentDic(DetectContentDic detectContentDic) {
        this.detectContentDic = detectContentDic;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_aqi_info")
    public AqiInfo getAqiInfo() {
        return this.aqiInfo;
    }
    
    public void setAqiInfo(AqiInfo aqiInfo) {
        this.aqiInfo = aqiInfo;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="report_time", length=19)
    public Date getReportTime() {
        return this.reportTime;
    }
    
    public void setReportTime(Date reportTime) {
        this.reportTime = reportTime;
    }
    
    @Column(name="is_daily")
    public Boolean getIsDaily() {
        return this.isDaily;
    }
    
    public void setIsDaily(Boolean isDaily) {
        this.isDaily = isDaily;
    }
    
    @Column(name="aqi", precision=12, scale=0)
    public Float getAqi() {
        return this.aqi;
    }
    
    public void setAqi(Float aqi) {
        this.aqi = aqi;
    }
    
    @Column(name="so2_aqi", precision=12, scale=0)
    public Float getSo2Aqi() {
        return this.so2Aqi;
    }
    
    public void setSo2Aqi(Float so2Aqi) {
        this.so2Aqi = so2Aqi;
    }
    
    @Column(name="o3_aqi", precision=12, scale=0)
    public Float getO3Aqi() {
        return this.o3Aqi;
    }
    
    public void setO3Aqi(Float o3Aqi) {
        this.o3Aqi = o3Aqi;
    }
    
    @Column(name="no2_aqi", precision=12, scale=0)
    public Float getNo2Aqi() {
        return this.no2Aqi;
    }
    
    public void setNo2Aqi(Float no2Aqi) {
        this.no2Aqi = no2Aqi;
    }
    
    @Column(name="pm10_aqi", precision=12, scale=0)
    public Float getPm10Aqi() {
        return this.pm10Aqi;
    }
    
    public void setPm10Aqi(Float pm10Aqi) {
        this.pm10Aqi = pm10Aqi;
    }
    
    @Column(name="pm25_aqi", precision=12, scale=0)
    public Float getPm25Aqi() {
        return this.pm25Aqi;
    }
    
    public void setPm25Aqi(Float pm25Aqi) {
        this.pm25Aqi = pm25Aqi;
    }
    
    @Column(name="co_aqi", precision=12, scale=0)
    public Float getCoAqi() {
        return this.coAqi;
    }
    
    public void setCoAqi(Float coAqi) {
        this.coAqi = coAqi;
    }




}


