package com.huihuan.eme.domain.db;
// Generated 2016-2-17 22:23:55 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DetectStationContentId generated by hbm2java
 */
@Embeddable
public class DetectStationContentId  implements java.io.Serializable {


     private Long idDectectStation;
     private Long idDetectContent;

    public DetectStationContentId() {
    }

    public DetectStationContentId(Long idDectectStation, Long idDetectContent) {
       this.idDectectStation = idDectectStation;
       this.idDetectContent = idDetectContent;
    }
   

    @Column(name="id_dectect_station", nullable=false)
    public Long getIdDectectStation() {
        return this.idDectectStation;
    }
    
    public void setIdDectectStation(Long idDectectStation) {
        this.idDectectStation = idDectectStation;
    }

    @Column(name="id_detect_content", nullable=false)
    public Long getIdDetectContent() {
        return this.idDetectContent;
    }
    
    public void setIdDetectContent(Long idDetectContent) {
        this.idDetectContent = idDetectContent;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetectStationContentId) ) return false;
		 DetectStationContentId castOther = ( DetectStationContentId ) other; 
         
		 return ( (this.getIdDectectStation()==castOther.getIdDectectStation()) || ( this.getIdDectectStation()!=null && castOther.getIdDectectStation()!=null && this.getIdDectectStation().equals(castOther.getIdDectectStation()) ) )
 && ( (this.getIdDetectContent()==castOther.getIdDetectContent()) || ( this.getIdDetectContent()!=null && castOther.getIdDetectContent()!=null && this.getIdDetectContent().equals(castOther.getIdDetectContent()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdDectectStation() == null ? 0 : this.getIdDectectStation().hashCode() );
         result = 37 * result + ( getIdDetectContent() == null ? 0 : this.getIdDetectContent().hashCode() );
         return result;
   }   


}


