package com.huihuan.eme.domain.db;
// Generated 2016-5-4 11:02:30 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * IaqiInfo generated by hbm2java
 */
@Entity
@Table(name="iaqi_info"
    ,catalog="eme"
)
public class IaqiInfo  implements java.io.Serializable {


     private Long id;
     private DetectFactor detectFactor;
     private AqiInfo aqiInfo;
     private Float clow;
     private Float chigh;

    public IaqiInfo() {
    }

    public IaqiInfo(DetectFactor detectFactor, AqiInfo aqiInfo, Float clow, Float chigh) {
       this.detectFactor = detectFactor;
       this.aqiInfo = aqiInfo;
       this.clow = clow;
       this.chigh = chigh;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_factor")
    public DetectFactor getDetectFactor() {
        return this.detectFactor;
    }
    
    public void setDetectFactor(DetectFactor detectFactor) {
        this.detectFactor = detectFactor;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_aqi_info")
    public AqiInfo getAqiInfo() {
        return this.aqiInfo;
    }
    
    public void setAqiInfo(AqiInfo aqiInfo) {
        this.aqiInfo = aqiInfo;
    }
    
    @Column(name="clow", precision=12, scale=0)
    public Float getClow() {
        return this.clow;
    }
    
    public void setClow(Float clow) {
        this.clow = clow;
    }
    
    @Column(name="chigh", precision=12, scale=0)
    public Float getChigh() {
        return this.chigh;
    }
    
    public void setChigh(Float chigh) {
        this.chigh = chigh;
    }




}


