package com.huihuan.eme.domain.db;
// Generated 2016-3-15 21:34:42 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PullantSource generated by hbm2java
 */
@Entity
@Table(name="pullant_source"
    ,catalog="eme"
)
public class PullantSource  implements java.io.Serializable {


     private Long id;
     private Company company;
     private String pullantName;
     private String description;
     private String lng;
     private String lat;
     private Date creationTime;
     private Set<DetectPullant> detectPullants = new HashSet<DetectPullant>(0);

    public PullantSource() {
    }

    public PullantSource(Company company, String pullantName, String description, String lng, String lat, Date creationTime, Set<DetectPullant> detectPullants) {
       this.company = company;
       this.pullantName = pullantName;
       this.description = description;
       this.lng = lng;
       this.lat = lat;
       this.creationTime = creationTime;
       this.detectPullants = detectPullants;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_company")
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
    
    @Column(name="pullant_name", length=32)
    public String getPullantName() {
        return this.pullantName;
    }
    
    public void setPullantName(String pullantName) {
        this.pullantName = pullantName;
    }
    
    @Column(name="description", length=256)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="lng", length=20)
    public String getLng() {
        return this.lng;
    }
    
    public void setLng(String lng) {
        this.lng = lng;
    }
    
    @Column(name="lat", length=20)
    public String getLat() {
        return this.lat;
    }
    
    public void setLat(String lat) {
        this.lat = lat;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="creation_time", length=10)
    public Date getCreationTime() {
        return this.creationTime;
    }
    
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="pullantSource")
    public Set<DetectPullant> getDetectPullants() {
        return this.detectPullants;
    }
    
    public void setDetectPullants(Set<DetectPullant> detectPullants) {
        this.detectPullants = detectPullants;
    }




}


