package com.huihuan.eme.domain.db;
// Generated 2016-3-15 21:08:08 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RiverCross generated by hbm2java
 */
@Entity
@Table(name="river_cross"
    ,catalog="eme"
)
public class RiverCross  implements java.io.Serializable {


     private Long id;
     private String lng;
     private String lat;
     private String crossName;
     private Date creationTime;
     private Set<DetectRiveRcross> detectRiveRcrosses = new HashSet<DetectRiveRcross>(0);

    public RiverCross() {
    }

    public RiverCross(String lng, String lat, String crossName, Date creationTime, Set<DetectRiveRcross> detectRiveRcrosses) {
       this.lng = lng;
       this.lat = lat;
       this.crossName = crossName;
       this.creationTime = creationTime;
       this.detectRiveRcrosses = detectRiveRcrosses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="lng", length=20)
    public String getLng() {
        return this.lng;
    }
    
    public void setLng(String lng) {
        this.lng = lng;
    }
    
    @Column(name="lat", length=20)
    public String getLat() {
        return this.lat;
    }
    
    public void setLat(String lat) {
        this.lat = lat;
    }
    
    @Column(name="cross_name", length=20)
    public String getCrossName() {
        return this.crossName;
    }
    
    public void setCrossName(String crossName) {
        this.crossName = crossName;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="creation_time", length=10)
    public Date getCreationTime() {
        return this.creationTime;
    }
    
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="riverCross")
    public Set<DetectRiveRcross> getDetectRiveRcrosses() {
        return this.detectRiveRcrosses;
    }
    
    public void setDetectRiveRcrosses(Set<DetectRiveRcross> detectRiveRcrosses) {
        this.detectRiveRcrosses = detectRiveRcrosses;
    }




}


