package com.huihuan.eme.domain.db;
// Generated 2016-3-15 21:08:08 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * WaterEnv generated by hbm2java
 */
@Entity
@Table(name="water_env"
    ,catalog="eme"
)
public class WaterEnv  implements java.io.Serializable {


     private Long id;
     private WaterEnvType waterEnvType;
     private EnvFunc envFunc;
     private String waterEnvName;
     private String lat;
     private String lng;
     private String emePerson;
     private String emeMobile;
     private Set<CompanyWaterEnv> companyWaterEnvs = new HashSet<CompanyWaterEnv>(0);

    public WaterEnv() {
    }

    public WaterEnv(WaterEnvType waterEnvType, EnvFunc envFunc, String waterEnvName, String lat, String lng, String emePerson, String emeMobile, Set<CompanyWaterEnv> companyWaterEnvs) {
       this.waterEnvType = waterEnvType;
       this.envFunc = envFunc;
       this.waterEnvName = waterEnvName;
       this.lat = lat;
       this.lng = lng;
       this.emePerson = emePerson;
       this.emeMobile = emeMobile;
       this.companyWaterEnvs = companyWaterEnvs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_water_env_type")
    public WaterEnvType getWaterEnvType() {
        return this.waterEnvType;
    }
    
    public void setWaterEnvType(WaterEnvType waterEnvType) {
        this.waterEnvType = waterEnvType;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_env_func")
    public EnvFunc getEnvFunc() {
        return this.envFunc;
    }
    
    public void setEnvFunc(EnvFunc envFunc) {
        this.envFunc = envFunc;
    }
    
    @Column(name="water_env_name", length=64)
    public String getWaterEnvName() {
        return this.waterEnvName;
    }
    
    public void setWaterEnvName(String waterEnvName) {
        this.waterEnvName = waterEnvName;
    }
    
    @Column(name="lat", length=20)
    public String getLat() {
        return this.lat;
    }
    
    public void setLat(String lat) {
        this.lat = lat;
    }
    
    @Column(name="lng", length=20)
    public String getLng() {
        return this.lng;
    }
    
    public void setLng(String lng) {
        this.lng = lng;
    }
    
    @Column(name="eme_person", length=20)
    public String getEmePerson() {
        return this.emePerson;
    }
    
    public void setEmePerson(String emePerson) {
        this.emePerson = emePerson;
    }
    
    @Column(name="eme_mobile", length=20)
    public String getEmeMobile() {
        return this.emeMobile;
    }
    
    public void setEmeMobile(String emeMobile) {
        this.emeMobile = emeMobile;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="waterEnv")
    public Set<CompanyWaterEnv> getCompanyWaterEnvs() {
        return this.companyWaterEnvs;
    }
    
    public void setCompanyWaterEnvs(Set<CompanyWaterEnv> companyWaterEnvs) {
        this.companyWaterEnvs = companyWaterEnvs;
    }




}


